openapi: 3.0.3
info:
  title: user-ms
  description: ""
  contact:
    email: bharghava.k@tibilsolutions.com
  version: 1.0.11
servers:
- url: /
tags:
- name: users
  description: Everything about authentication
paths:
  /user/otp:
    post:
      tags:
      - users
      summary: generate otp
      description: generate otp
      operationId: generateOtp
      requestBody:
        description: mobile number required
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/user_otp_body'
      responses:
        "200":
          description: Successfull operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
        "400":
          description: bad request
      x-swagger-router-controller: Users
    patch:
      tags:
      - users
      summary: verify otp registered
      description: verify otp
      operationId: verifyotp
      requestBody:
        description: verifyotp
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/otpBody'
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_1'
        "400":
          description: invalid data
        "422":
          description: Validation exception
      x-swagger-router-controller: Users
  /user/secrets:
    post:
      tags:
      - users
      summary: Check the mobile number registered
      description: check mobile number registered
      operationId: token
      requestBody:
        description: mobile number
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/user_secrets_body'
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/secrets'
            application/xml:
              schema:
                $ref: '#/components/schemas/secrets'
        "422":
          description: Validation exception
      x-swagger-router-controller: Users
  /user/accounts/get:
    post:
      tags:
      - users
      summary: get account details
      description: Account Details
      operationId: accountDetails
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/accounts_get_body'
      responses:
        "200":
          description: Successfull Opertion
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_2'
      x-swagger-router-controller: Users
  /user/account/upi/get:
    post:
      tags:
      - users
      summary: get static qrcode
      description: ' '
      operationId: chcekMobile
      requestBody:
        description: mobile number
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/auth'
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/upi'
        "400":
          description: invalid data
        "422":
          description: Validation exception
      x-swagger-router-controller: Users
  /user/preferences:
    put:
      tags:
      - users
      summary: update preferences
      description: ""
      operationId: preference
      requestBody:
        description: preferences
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/user_preferences_body'
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_3'
        "400":
          description: invalid data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_400'
      x-swagger-router-controller: Users
  /tnc/get:
    post:
      tags:
      - users
      summary: update preferences
      description: ""
      operationId: tnc
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_4'
        "400":
          description: invalid data
      x-swagger-router-controller: Users
components:
  schemas:
    otpBody:
      type: object
      properties:
        otp:
          type: integer
          format: int64
          example: 873443
        mobile_number:
          type: string
          example: "8375437533"
        device_id:
          type: string
          example: "345343453"
        identification:
          type: string
          example: "234554"
    upi:
      type: object
      properties:
        code:
          type: integer
          example: 2000
        data:
          $ref: '#/components/schemas/upi_data'
      example:
        code: 2000
        data:
          customer_vpa: JSFidb012345678bd12345p6128125ded45
          customer_name: abc
          base64qrcode: iVBORw0KGgoAAAANSUhEUgAAAlgAAAQaCAIAAAAQRJHWAACAAElEQVR42uzdebQV1Z33/
            /vHs1avleTX/azn6d/KahXBCZO2FaJJJ4b8YkfMk8e222hit9HE2CYYTdoMKlwVEASTiKjgEHECUQ
            ERZXAAHBhFRFBEAQ0oMyhXLncegAt3+H3P3
    secrets:
      type: object
      properties:
        code:
          type: integer
          example: 2000
        data:
          $ref: '#/components/schemas/secrets_data'
      example:
        code: 2000
        data:
          access_token: iVBORw0KGgoAAAANSUhEUgAAAlgAAAQaCAIAAAAQRJHWAACAAElEQVR42uzdebQV1Z33/
            /vHs1avleTX/azn6d/KahXBCZO2FaJJJ4b8YkfMk8e222hit9HE2CYYTdoMKlwVEASTiKjgEHECUQ
            ERZXAAHBhFRFBEAQ0oMyhXLncegAt3+H3P3
          refresh_token: iVBORw0KGgoAAAANSUhEUgAAAlgAAAQaCAIAAAAQRJHWAACAAElEQVR42uzdebQV1Z33/
            /vHs1avleTX/azn6d/KahXBCZO2FaJJJ4b8YkfMk8e222hit9HE2CYYTdoMKlwVEASTiKjgEHECUQ
            ERZXAAHBhFRFBEAQ0oMyhXLncegAt3+H3P3
          default_preferences:
            language: en
            mute: "true"
          uuid: fsndfj2454
    auth:
      type: object
      properties:
        mobile_number:
          type: string
          example: "9283942989"
        account_number:
          type: string
          example: "26564462343569"
    user_otp_body:
      type: object
      properties:
        mobile_number:
          type: string
          example: "23333394"
    inline_response_200:
      type: object
      properties:
        code:
          type: integer
          example: 2000
        identification:
          type: string
          example: "453453"
      example:
        code: 2000
        identification: "453453"
    inline_response_200_1:
      type: object
      properties:
        code:
          type: integer
          example: 2000
        message:
          type: string
          example: ok
      example:
        code: 2000
        message: ok
    user_secrets_body:
      type: object
      properties:
        mobile_number:
          type: string
          example: "235435656"
        mpin:
          type: integer
          example: 12432
    accounts_get_body:
      type: object
      properties:
        mobile:
          type: string
          example: "1215545454"
    inline_response_200_2:
      type: object
      properties:
        code:
          type: integer
          example: 2000
        data:
          $ref: '#/components/schemas/inline_response_200_2_data'
      example:
        code: 2000
        data:
          accounts: "[{\"customerId\":\"11111111\",\"customerReferenceNumber\":\"\
            5674267906535678\",\"customerFullName\":\"Sample Kumar\",\"mobileNumber\"\
            :\"9999999999\",\"accountId\":\"xxxxxxxxxxxx3984\",\"accountType\":\"\
            CURRENT\",\"accountStatus\":\"ACCOUNT OPEN REGULAR\",\"IFSCCode\":\"JSFB0004534\"\
            ,\"aeba\":\"Y\"},{\"customerId\":\"2222222\",\"customerReferenceNumber\"\
            :\"5674267906535678\",\"customerFullName\":\"Sample Kumar\",\"mobileNumber\"\
            :\"9999999999\",\"accountId\":\"xxxxxxxxxxxx3984\",\"accountType\":\"\
            CURRENT\",\"accountStatus\":\"ACCOUNT OPEN REGULAR\",\"IFSCCode\":\"JSFB0004534\"\
            ,\"aeba\":\"Y\"}]"
    user_preferences_body:
      type: object
      properties:
        uuid:
          type: string
          example: bdsjfj145645-sdfnsdnf2sdf
        language:
          type: string
          example: kn
        mute:
          type: string
          example: "true"
    inline_response_200_3:
      type: object
      properties:
        code:
          type: integer
          example: 2000
        message:
          type: string
          example: updated successfully
      example:
        code: 2000
        message: updated successfully
    inline_response_400:
      type: object
      properties:
        code:
          type: integer
          example: 1000
        message:
          type: string
          example: invalid/missing uuid
    inline_response_200_4:
      type: object
      properties:
        code:
          type: integer
          example: 2000
        url:
          type: string
          example: https://tnc.com
      example:
        code: 2000
        url: https://tnc.com
    upi_data:
      type: object
      properties:
        base64qrcode:
          type: string
          example: iVBORw0KGgoAAAANSUhEUgAAAlgAAAQaCAIAAAAQRJHWAACAAElEQVR42uzdebQV1Z33/
            /vHs1avleTX/azn6d/KahXBCZO2FaJJJ4b8YkfMk8e222hit9HE2CYYTdoMKlwVEASTiKjgEHECUQ
            ERZXAAHBhFRFBEAQ0oMyhXLncegAt3+H3P3
        customer_name:
          type: string
          example: abc
        customer_vpa:
          type: string
          example: JSFidb012345678bd12345p6128125ded45
      example:
        customer_vpa: JSFidb012345678bd12345p6128125ded45
        customer_name: abc
        base64qrcode: iVBORw0KGgoAAAANSUhEUgAAAlgAAAQaCAIAAAAQRJHWAACAAElEQVR42uzdebQV1Z33/
          /vHs1avleTX/azn6d/KahXBCZO2FaJJJ4b8YkfMk8e222hit9HE2CYYTdoMKlwVEASTiKjgEHECUQ
          ERZXAAHBhFRFBEAQ0oMyhXLncegAt3+H3P3
    secrets_data_default_preferences:
      type: object
      properties:
        language:
          type: string
          example: en
        mute:
          type: string
          example: "true"
      example:
        language: en
        mute: "false"
    secrets_data:
      type: object
      properties:
        uuid:
          type: string
          example: fsndfj2454
        access_token:
          type: string
          example: iVBORw0KGgoAAAANSUhEUgAAAlgAAAQaCAIAAAAQRJHWAACAAElEQVR42uzdebQV1Z33/
            /vHs1avleTX/azn6d/KahXBCZO2FaJJJ4b8YkfMk8e222hit9HE2CYYTdoMKlwVEASTiKjgEHECUQ
            ERZXAAHBhFRFBEAQ0oMyhXLncegAt3+H3P3
        refresh_token:
          type: string
          example: iVBORw0KGgoAAAANSUhEUgAAAlgAAAQaCAIAAAAQRJHWAACAAElEQVR42uzdebQV1Z33/
            /vHs1avleTX/azn6d/KahXBCZO2FaJJJ4b8YkfMk8e222hit9HE2CYYTdoMKlwVEASTiKjgEHECUQ
            ERZXAAHBhFRFBEAQ0oMyhXLncegAt3+H3P3
        default_preferences:
          $ref: '#/components/schemas/secrets_data_default_preferences'
      example:
        access_token: iVBORw0KGgoAAAANSUhEUgAAAlgAAAQaCAIAAAAQRJHWAACAAElEQVR42uzdebQV1Z33/
          /vHs1avleTX/azn6d/KahXBCZO2FaJJJ4b8YkfMk8e222hit9HE2CYYTdoMKlwVEASTiKjgEHECUQ
          ERZXAAHBhFRFBEAQ0oMyhXLncegAt3+H3P3
        refresh_token: iVBORw0KGgoAAAANSUhEUgAAAlgAAAQaCAIAAAAQRJHWAACAAElEQVR42uzdebQV1Z33/
          /vHs1avleTX/azn6d/KahXBCZO2FaJJJ4b8YkfMk8e222hit9HE2CYYTdoMKlwVEASTiKjgEHECUQ
          ERZXAAHBhFRFBEAQ0oMyhXLncegAt3+H3P3
        default_preferences:
          language: en
          mute: "true"
        uuid: fsndfj2454
    inline_response_200_2_data_accounts:
      type: object
      properties:
        customerId:
          type: string
        customerReferenceNumber:
          type: string
        customerFullName:
          type: string
        mobileNumber:
          type: string
        accountId:
          type: string
        accountType:
          type: string
        accountStatus:
          type: string
        IFSCCode:
          type: string
        aeba:
          type: string
      example: "[{\"customerId\":\"11111111\",\"customerReferenceNumber\":\"5674267906535678\"\
        ,\"customerFullName\":\"Sample Kumar\",\"mobileNumber\":\"9999999999\",\"\
        accountId\":\"xxxxxxxxxxxx3984\",\"accountType\":\"CURRENT\",\"accountStatus\"\
        :\"ACCOUNT OPEN REGULAR\",\"IFSCCode\":\"JSFB0004534\",\"aeba\":\"Y\"},{\"\
        customerId\":\"11111111\",\"customerReferenceNumber\":\"5674267906535678\"\
        ,\"customerFullName\":\"Sample Kumar\",\"mobileNumber\":\"9999999999\",\"\
        accountId\":\"xxxxxxxxxxxx3984\",\"accountType\":\"CURRENT\",\"accountStatus\"\
        :\"ACCOUNT OPEN REGULAR\",\"IFSCCode\":\"JSFB0004534\",\"aeba\":\"Y\"}]"
    inline_response_200_2_data:
      type: object
      properties:
        accounts:
          $ref: '#/components/schemas/inline_response_200_2_data_accounts'
      example:
        accounts: "[{\"customerId\":\"11111111\",\"customerReferenceNumber\":\"5674267906535678\"\
          ,\"customerFullName\":\"Sample Kumar\",\"mobileNumber\":\"9999999999\",\"\
          accountId\":\"xxxxxxxxxxxx3984\",\"accountType\":\"CURRENT\",\"accountStatus\"\
          :\"ACCOUNT OPEN REGULAR\",\"IFSCCode\":\"JSFB0004534\",\"aeba\":\"Y\"},{\"\
          customerId\":\"11111111\",\"customerReferenceNumber\":\"5674267906535678\"\
          ,\"customerFullName\":\"Sample Kumar\",\"mobileNumber\":\"9999999999\",\"\
          accountId\":\"xxxxxxxxxxxx3984\",\"accountType\":\"CURRENT\",\"accountStatus\"\
          :\"ACCOUNT OPEN REGULAR\",\"IFSCCode\":\"JSFB0004534\",\"aeba\":\"Y\"}]"
